import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("../data/raw/HR-Employee-Attrition.csv")

df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2


In [4]:
df.shape

(1470, 35)

In [5]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [6]:
features = [
    "Age",
    "Department",
    "JobRole",
    "MonthlyIncome",
    "JobLevel",
    "OverTime",
    "JobSatisfaction",
    "WorkLifeBalance",
    "YearsAtCompany",
    "BusinessTravel"
]

X = df[features]

y = df["Attrition"]

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [9]:
X_train.shape, X_test.shape

((1176, 10), (294, 10))

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [11]:
numeric_features = [
    "Age",
    "MonthlyIncome",
    "JobLevel",
    "JobSatisfaction",
    "WorkLifeBalance",
    "YearsAtCompany"
]

categorical_features = [
    "Department",
    "JobRole",
    "OverTime",
    "BusinessTravel"
]

In [12]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)

In [13]:
X_train_processed = preprocessor.fit_transform(X_train)

X_test_processed = preprocessor.transform(X_test)

In [14]:
X_train_processed.shape

(1176, 23)

In [15]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

model.fit(X_train_processed, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,42
,solver,'lbfgs'
,max_iter,1000
,multi_class,'deprecated'


In [16]:
print("Model trained successfully!")

Model trained successfully!


In [17]:
y_pred = model.predict(X_test_processed)

In [18]:
len(y_pred)

294

In [19]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)

Accuracy:  0.8571428571428571


In [20]:
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

In [21]:
X_test_processed.shape

(294, 23)

In [22]:
from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(y_test, y_pred, pos_label="Yes")
recall = recall_score(y_test, y_pred, pos_label="Yes")
f1 = f1_score(y_test, y_pred, pos_label="Yes")

print("Precision:",precision)
print("Recall:",recall)
print("F1 score:",f1)

Precision: 0.7272727272727273
Recall: 0.1702127659574468
F1 score: 0.27586206896551724


In [23]:
from collections import Counter

Counter(y_pred)

Counter({'No': 283, 'Yes': 11})

In [24]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[244   3]
 [ 39   8]]


In [25]:
y_prob = model.predict_proba(X_test_processed)[:, 1]

In [26]:
y_prob[:10]

array([0.27333652, 0.01634287, 0.10616761, 0.02867738, 0.26261986,
       0.11633638, 0.06109041, 0.01939408, 0.02753829, 0.15837731])

In [27]:
from sklearn.metrics import roc_auc_score

roc_auc = roc_auc_score(y_test, y_prob)

print("ROC-AUC:", roc_auc)

ROC-AUC: 0.7305538806098717


In [28]:
y_threshold_40 = np.where(y_prob >= 0.40, "Yes", "No")

from collections import Counter

Counter(y_threshold_40)

Counter({np.str_('No'): 271, np.str_('Yes'): 23})

In [29]:
cm_40 = confusion_matrix(y_test, y_threshold_40)

print(cm_40)

[[241   6]
 [ 30  17]]


In [30]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(
    random_state=42,
    max_depth=5
)

dt_model.fit(X_train_processed, y_train)

print("Decision Tree trained successfully!")

Decision Tree trained successfully!


In [31]:
dt_pred = dt_model.predict(X_test_processed)

In [32]:
from collections import Counter

Counter(dt_pred)

Counter({'No': 274, 'Yes': 20})

In [33]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

dt_accuracy = accuracy_score(y_test, dt_pred)

dt_precision = precision_score(
    y_test,
    dt_pred,
    pos_label="Yes"
)

dt_recall = recall_score(
    y_test,
    dt_pred,
    pos_label="Yes"
)

dt_f1 = f1_score(
    y_test,
    dt_pred,
    pos_label="Yes"
)

print("Accuracy:", dt_accuracy)
print("Precision:", dt_precision)
print("Recall:", dt_recall)
print("F1 Score:", dt_f1)

Accuracy: 0.8197278911564626
Precision: 0.35
Recall: 0.14893617021276595
F1 Score: 0.208955223880597


In [34]:
from sklearn.metrics import confusion_matrix

dt_cm = confusion_matrix(y_test, dt_pred)

print(dt_cm)

[[234  13]
 [ 40   7]]


In [35]:
dt_prob = dt_model.predict_proba(X_test_processed)[:, 1]

print(dt_prob[:10])

[0.52941176 0.07649254 0.01724138 0.01724138 0.4        0.0619469
 0.0619469  0.01724138 0.07649254 0.        ]


In [36]:
from sklearn.metrics import roc_auc_score

dt_roc_auc = roc_auc_score(y_test, dt_prob)

print("Decision Tree ROC-AUC:", dt_roc_auc)

Decision Tree ROC-AUC: 0.6663364630889826


In [37]:
comparison = {
    "Metric": ["Accuracy", "Precision", "Recall", "F1 Score", "ROC-AUC"],
    "Logistic Regression": [
        accuracy,
        precision,
        recall,
        f1,
        roc_auc
    ],
    "Decision Tree": [
        dt_accuracy,
        dt_precision,
        dt_recall,
        dt_f1,
        dt_roc_auc
    ]
}

comparison_df = pd.DataFrame(comparison)

comparison_df

,Metric,Logistic Regression,Decision Tree
0,Accuracy,0.857143,0.819728
1,Precision,0.727273,0.350000
2,Recall,0.170213,0.148936
3,F1 Score,0.275862,0.208955
4,ROC-AUC,0.730554,0.666336


In [38]:
comparison = {
    "Metric": ["Accuracy", "Precision", "Recall", "F1 Score", "ROC-AUC"],
    
    "Logistic Regression": [
        accuracy,
        precision,
        recall,
        f1,
        roc_auc
    ],
    
    "Decision Tree": [
        dt_accuracy,
        dt_precision,
        dt_recall,
        dt_f1,
        dt_roc_auc
    ]
}

comparison_df = pd.DataFrame(comparison)

comparison_df

,Metric,Logistic Regression,Decision Tree
0,Accuracy,0.857143,0.819728
1,Precision,0.727273,0.350000
2,Recall,0.170213,0.148936
3,F1 Score,0.275862,0.208955
4,ROC-AUC,0.730554,0.666336


In [39]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=6,
    random_state=42
)

rf_model.fit(X_train_processed, y_train)

print("Random Forest trained successfully!")

Random Forest trained successfully!


In [40]:
rf_pred = rf_model.predict(X_test_processed)

print("Random Forest predictions completed!")

Random Forest predictions completed!


In [41]:
from collections import Counter

Counter(rf_pred)

Counter({'No': 279, 'Yes': 15})

In [42]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

rf_accuracy = accuracy_score(y_test, rf_pred)

rf_precision = precision_score(
    y_test,
    rf_pred,
    pos_label="Yes"
)

rf_recall = recall_score(
    y_test,
    rf_pred,
    pos_label="Yes"
)

rf_f1 = f1_score(
    y_test,
    rf_pred,
    pos_label="Yes"
)

print("Accuracy:", rf_accuracy)
print("Precision:", rf_precision)
print("Recall:", rf_recall)
print("F1 Score:", rf_f1)

Accuracy: 0.8571428571428571
Precision: 0.6666666666666666
Recall: 0.2127659574468085
F1 Score: 0.3225806451612903


In [43]:
rf_prob = rf_model.predict_proba(X_test_processed)[:, 1]

rf_roc_auc = roc_auc_score(y_test, rf_prob)

print("Random Forest ROC-AUC:", rf_roc_auc)

Random Forest ROC-AUC: 0.7662158669997416


In [44]:
comparison = {
    "Metric": [
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score",
        "ROC-AUC"
    ],
    
    "Logistic Regression": [
        accuracy,
        precision,
        recall,
        f1,
        roc_auc
    ],
    
    "Decision Tree": [
        dt_accuracy,
        dt_precision,
        dt_recall,
        dt_f1,
        dt_roc_auc
    ],
    
    "Random Forest": [
        rf_accuracy,
        rf_precision,
        rf_recall,
        rf_f1,
        rf_roc_auc
    ]
}

comparison_df = pd.DataFrame(comparison)

comparison_df

,Metric,Logistic Regression,Decision Tree,Random Forest
0,Accuracy,0.857143,0.819728,0.857143
1,Precision,0.727273,0.350000,0.666667
2,Recall,0.170213,0.148936,0.212766
3,F1 Score,0.275862,0.208955,0.322581
4,ROC-AUC,0.730554,0.666336,0.766216


In [45]:
rf_balanced = RandomForestClassifier(
    n_estimators=200,
    max_depth=6,
    class_weight="balanced",
    random_state=42
)

rf_balanced.fit(X_train_processed, y_train)

print("Balanced Random Forest trained successfully!")

Balanced Random Forest trained successfully!


In [46]:
rf_balanced_pred = rf_balanced.predict(X_test_processed)

print("Balanced Random Forest predictions completed!")

Balanced Random Forest predictions completed!


In [47]:
from collections import Counter

Counter(rf_balanced_pred)

Counter({'No': 234, 'Yes': 60})

In [48]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

rf_balanced_accuracy = accuracy_score(y_test, rf_balanced_pred)

rf_balanced_precision = precision_score(
    y_test,
    rf_balanced_pred,
    pos_label="Yes"
)

rf_balanced_recall = recall_score(
    y_test,
    rf_balanced_pred,
    pos_label="Yes"
)

rf_balanced_f1 = f1_score(
    y_test,
    rf_balanced_pred,
    pos_label="Yes"
)

print("Accuracy:", rf_balanced_accuracy)
print("Precision:", rf_balanced_precision)
print("Recall:", rf_balanced_recall)
print("F1 Score:", rf_balanced_f1)

Accuracy: 0.8061224489795918
Precision: 0.4166666666666667
Recall: 0.5319148936170213
F1 Score: 0.4672897196261682


In [49]:
rf_balanced_prob = rf_balanced.predict_proba(X_test_processed)[:, 1]

rf_balanced_roc_auc = roc_auc_score(
    y_test,
    rf_balanced_prob
)

print("Balanced Random Forest ROC-AUC:", rf_balanced_roc_auc)

Balanced Random Forest ROC-AUC: 0.7475665431992419


In [50]:
comparison_balanced = {
    "Metric": [
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score",
        "ROC-AUC"
    ],

    "Logistic Regression": [
        accuracy,
        precision,
        recall,
        f1,
        roc_auc
    ],

    "Decision Tree": [
        dt_accuracy,
        dt_precision,
        dt_recall,
        dt_f1,
        dt_roc_auc
    ],

    "Random Forest": [
        rf_accuracy,
        rf_precision,
        rf_recall,
        rf_f1,
        rf_roc_auc
    ],

    "Balanced Random Forest": [
        rf_balanced_accuracy,
        rf_balanced_precision,
        rf_balanced_recall,
        rf_balanced_f1,
        rf_balanced_roc_auc
    ]
}

comparison_balanced_df = pd.DataFrame(comparison_balanced)

comparison_balanced_df

,Metric,Logistic Regression,Decision Tree,Random Forest,Balanced Random Forest
0,Accuracy,0.857143,0.819728,0.857143,0.806122
1,Precision,0.727273,0.350000,0.666667,0.416667
2,Recall,0.170213,0.148936,0.212766,0.531915
3,F1 Score,0.275862,0.208955,0.322581,0.467290
4,ROC-AUC,0.730554,0.666336,0.766216,0.747567


In [51]:
from sklearn.metrics import confusion_matrix

rf_balanced_cm = confusion_matrix(
    y_test,
    rf_balanced_pred
)

print(rf_balanced_cm)

[[212  35]
 [ 22  25]]


In [52]:
from sklearn.model_selection import train_test_split

X_train_inner, X_val, y_train_inner, y_val = train_test_split(
    X_train,
    y_train,
    test_size=0.20,
    random_state=42,
    stratify=y_train
)

print("Training data:", X_train_inner.shape)
print("Validation data:", X_val.shape)

Training data: (940, 10)
Validation data: (236, 10)


In [53]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

validation_preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)

X_train_inner_processed = validation_preprocessor.fit_transform(X_train_inner)
X_val_processed = validation_preprocessor.transform(X_val)

print("Training features:", X_train_inner_processed.shape)
print("Validation features:", X_val_processed.shape)

Training features: (940, 23)
Validation features: (236, 23)


In [54]:
from sklearn.ensemble import RandomForestClassifier

rf_validation = RandomForestClassifier(
    n_estimators=200,
    max_depth=6,
    class_weight="balanced",
    random_state=42
)

rf_validation.fit(
    X_train_inner_processed,
    y_train_inner
)

print("Validation Random Forest trained successfully!")

Validation Random Forest trained successfully!


In [55]:
rf_val_prob = rf_validation.predict_proba(X_val_processed)[:, 1]

print(rf_val_prob[:10])

[0.32097416 0.21508241 0.38254896 0.20993423 0.16170321 0.15206007
 0.22504731 0.32189587 0.46332555 0.18214286]


In [56]:
import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score

thresholds = np.arange(0.10, 0.61, 0.05)

for threshold in thresholds:
    y_val_threshold = np.where(
        rf_val_prob >= threshold,
        "Yes",
        "No"
    )

    precision = precision_score(
        y_val,
        y_val_threshold,
        pos_label="Yes"
    )

    recall = recall_score(
        y_val,
        y_val_threshold,
        pos_label="Yes"
    )

    f1 = f1_score(
        y_val,
        y_val_threshold,
        pos_label="Yes"
    )

    print(
        f"Threshold: {threshold:.2f} | "
        f"Precision: {precision:.2f} | "
        f"Recall: {recall:.2f} | "
        f"F1: {f1:.2f}"
    )

Threshold: 0.10 | Precision: 0.17 | Recall: 1.00 | F1: 0.29
Threshold: 0.15 | Precision: 0.17 | Recall: 0.95 | F1: 0.29
Threshold: 0.20 | Precision: 0.19 | Recall: 0.92 | F1: 0.32
Threshold: 0.25 | Precision: 0.23 | Recall: 0.89 | F1: 0.37
Threshold: 0.30 | Precision: 0.25 | Recall: 0.82 | F1: 0.39
Threshold: 0.35 | Precision: 0.32 | Recall: 0.79 | F1: 0.45
Threshold: 0.40 | Precision: 0.41 | Recall: 0.68 | F1: 0.51
Threshold: 0.45 | Precision: 0.43 | Recall: 0.58 | F1: 0.49
Threshold: 0.50 | Precision: 0.55 | Recall: 0.58 | F1: 0.56
Threshold: 0.55 | Precision: 0.53 | Recall: 0.42 | F1: 0.47
Threshold: 0.60 | Precision: 0.54 | Recall: 0.39 | F1: 0.45


In [57]:
from sklearn.ensemble import RandomForestClassifier

final_rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=6,
    class_weight="balanced",
    random_state=42
)

final_rf.fit(
    X_train_processed,
    y_train
)

print("Final Balanced Random Forest trained successfully!")

Final Balanced Random Forest trained successfully!


In [58]:
# Predict attrition probabilities on the final test set
final_test_prob = final_rf.predict_proba(X_test_processed)[:, 1]

# Apply our selected threshold
final_test_pred = np.where(
    final_test_prob >= 0.50,
    "Yes",
    "No"
)

print(final_test_pred[:10])

['Yes' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No']


In [59]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)

accuracy = accuracy_score(y_test, final_test_pred)
precision = precision_score(y_test, final_test_pred, pos_label="Yes")
recall = recall_score(y_test, final_test_pred, pos_label="Yes")
f1 = f1_score(y_test, final_test_pred, pos_label="Yes")
roc_auc = roc_auc_score(
    (y_test == "Yes").astype(int),
    final_test_prob
)

print("Final Model Results")
print("-------------------")
print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1 Score : {f1:.4f}")
print(f"ROC-AUC  : {roc_auc:.4f}")

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, final_test_pred))

Final Model Results
-------------------
Accuracy : 0.8061
Precision: 0.4167
Recall   : 0.5319
F1 Score : 0.4673
ROC-AUC  : 0.7476

Confusion Matrix:
[[212  35]
 [ 22  25]]


In [60]:
from sklearn.pipeline import Pipeline

final_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", RandomForestClassifier(
            n_estimators=200,
            max_depth=6,
            class_weight="balanced",
            random_state=42
        ))
    ]
)

final_pipeline.fit(X_train, y_train)

print("Final ML pipeline trained successfully!")

Final ML pipeline trained successfully!


In [61]:
# Predict probabilities using the complete pipeline
pipeline_test_prob = final_pipeline.predict_proba(X_test)[:, 1]

# Apply our selected threshold
pipeline_test_pred = np.where(
    pipeline_test_prob >= 0.50,
    "Yes",
    "No"
)

print("First 10 probabilities:")
print(pipeline_test_prob[:10])

print("\nFirst 10 predictions:")
print(pipeline_test_pred[:10])

First 10 probabilities:
[0.63579299 0.19972396 0.28723582 0.12698436 0.50913216 0.22181546
 0.29448622 0.11303114 0.17515945 0.36755959]

First 10 predictions:
['Yes' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No']


In [62]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)

pipeline_accuracy = accuracy_score(y_test, pipeline_test_pred)
pipeline_precision = precision_score(
    y_test,
    pipeline_test_pred,
    pos_label="Yes"
)
pipeline_recall = recall_score(
    y_test,
    pipeline_test_pred,
    pos_label="Yes"
)
pipeline_f1 = f1_score(
    y_test,
    pipeline_test_pred,
    pos_label="Yes"
)
pipeline_roc_auc = roc_auc_score(
    (y_test == "Yes").astype(int),
    pipeline_test_prob
)

print("Pipeline Model Results")
print("----------------------")
print(f"Accuracy : {pipeline_accuracy:.4f}")
print(f"Precision: {pipeline_precision:.4f}")
print(f"Recall   : {pipeline_recall:.4f}")
print(f"F1 Score : {pipeline_f1:.4f}")
print(f"ROC-AUC  : {pipeline_roc_auc:.4f}")

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, pipeline_test_pred))

Pipeline Model Results
----------------------
Accuracy : 0.8061
Precision: 0.4167
Recall   : 0.5319
F1 Score : 0.4673
ROC-AUC  : 0.7476

Confusion Matrix:
[[212  35]
 [ 22  25]]


In [63]:
import joblib

joblib.dump(
    final_pipeline,
    "../python/attrition_model.pkl"
)

print("Model saved successfully!")

Model saved successfully!


In [64]:
print("Dataset Shape:")
print(df.shape)

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nAttrition Distribution:")
print(df["Attrition"].value_counts())

print("\nAttrition Percentage:")
print(df["Attrition"].value_counts(normalize=True) * 100)

Dataset Shape:
(1470, 35)

Data Types:
Age                          int64
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel

In [65]:
numeric_columns = [
    "Age",
    "DailyRate",
    "DistanceFromHome",
    "Education",
    "EnvironmentSatisfaction",
    "HourlyRate",
    "JobInvolvement",
    "JobLevel",
    "JobSatisfaction",
    "MonthlyIncome",
    "MonthlyRate",
    "NumCompaniesWorked",
    "PercentSalaryHike",
    "PerformanceRating",
    "RelationshipSatisfaction",
    "StockOptionLevel",
    "TotalWorkingYears",
    "TrainingTimesLastYear",
    "WorkLifeBalance",
    "YearsAtCompany",
    "YearsInCurrentRole",
    "YearsSinceLastPromotion",
    "YearsWithCurrManager"
]

numeric_summary = df[numeric_columns].describe().T

numeric_summary

,count,mean,std,min,25%,50%,75%,max
Age,1470.0,36.923810,9.135373,18.0,30.0,36.0,43.00,60.0
DailyRate,1470.0,802.485714,403.509100,102.0,465.0,802.0,1157.00,1499.0
DistanceFromHome,1470.0,9.192517,8.106864,1.0,2.0,7.0,14.00,29.0
Education,1470.0,2.912925,1.024165,1.0,2.0,3.0,4.00,5.0
EnvironmentSatisfaction,1470.0,2.721769,1.093082,1.0,2.0,3.0,4.00,4.0
HourlyRate,1470.0,65.891156,20.329428,30.0,48.0,66.0,83.75,100.0
JobInvolvement,1470.0,2.729932,0.711561,1.0,2.0,3.0,3.00,4.0
JobLevel,1470.0,2.063946,1.106940,1.0,1.0,2.0,3.00,5.0
JobSatisfaction,1470.0,2.728571,1.102846,1.0,2.0,3.0,4.00,4.0
MonthlyIncome,1470.0,6502.931293,4707.956783,1009.0,2911.0,4919.0,8379.00,19999.0


In [66]:
categorical_columns = [
    "BusinessTravel",
    "Department",
    "EducationField",
    "Gender",
    "JobRole",
    "MaritalStatus",
    "OverTime"
]

for column in categorical_columns:
    print(f"\n{'=' * 50}")
    print(column)
    print(f"{'=' * 50}")
    print(df[column].value_counts())
    print("\nPercentage:")
    print((df[column].value_counts(normalize=True) * 100).round(2))


BusinessTravel
BusinessTravel
Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: count, dtype: int64

Percentage:
BusinessTravel
Travel_Rarely        70.95
Travel_Frequently    18.84
Non-Travel           10.20
Name: proportion, dtype: float64

Department
Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

Percentage:
Department
Research & Development    65.37
Sales                     30.34
Human Resources            4.29
Name: proportion, dtype: float64

EducationField
EducationField
Life Sciences       606
Medical             464
Marketing           159
Technical Degree    132
Other                82
Human Resources      27
Name: count, dtype: int64

Percentage:
EducationField
Life Sciences       41.22
Medical             31.56
Marketing           10.82
Technical Degree     8.98
Other                5.58
Human Resources      1.84
Name: proportion, dtype: float64

Gender
Gende

In [67]:
department_attrition = pd.crosstab(
    df["Department"],
    df["Attrition"]
)

department_attrition["Attrition_Rate"] = (
    department_attrition["Yes"]
    / department_attrition.sum(axis=1)
    * 100
).round(2)

department_attrition

Attrition,No,Yes,Attrition_Rate
Department,,,
Human Resources,51,12,19.05
Research & Development,828,133,13.84
Sales,354,92,20.63


In [68]:
jobrole_attrition = pd.crosstab(
    df["JobRole"],
    df["Attrition"]
)

jobrole_attrition["Attrition_Rate"] = (
    jobrole_attrition["Yes"]
    / jobrole_attrition.sum(axis=1)
    * 100
).round(2)

jobrole_attrition.sort_values(
    "Attrition_Rate",
    ascending=False
)

Attrition,No,Yes,Attrition_Rate
JobRole,,,
Sales Representative,50,33,39.76
Laboratory Technician,197,62,23.94
Human Resources,40,12,23.08
Sales Executive,269,57,17.48
Research Scientist,245,47,16.10
Manufacturing Director,135,10,6.90
Healthcare Representative,122,9,6.87
Manager,97,5,4.90
Research Director,78,2,2.50


In [69]:
jobrole_attrition = pd.crosstab(
    df["JobRole"],
    df["Attrition"]
)

jobrole_attrition["Attrition_Rate"] = (
    jobrole_attrition["Yes"]
    / jobrole_attrition.sum(axis=1)
    * 100
).round(2)

jobrole_attrition.sort_values(
    "Attrition_Rate",
    ascending=False
)

Attrition,No,Yes,Attrition_Rate
JobRole,,,
Sales Representative,50,33,39.76
Laboratory Technician,197,62,23.94
Human Resources,40,12,23.08
Sales Executive,269,57,17.48
Research Scientist,245,47,16.10
Manufacturing Director,135,10,6.90
Healthcare Representative,122,9,6.87
Manager,97,5,4.90
Research Director,78,2,2.50


In [72]:
overtime_attrition = pd.crosstab(
    df["OverTime"],
    df["Attrition"]
)

overtime_attrition["Attrition_Rate"] = (
    overtime_attrition["Yes"]
    / overtime_attrition.sum(axis=1)
    * 100
).round(2)

overtime_attrition

Attrition,No,Yes,Attrition_Rate
OverTime,,,
No,944,110,10.44
Yes,289,127,30.53


In [73]:
job_satisfaction_attrition = pd.crosstab(
    df["JobSatisfaction"],
    df["Attrition"]
)

job_satisfaction_attrition["Attrition_Rate"] = (
    job_satisfaction_attrition["Yes"]
    / job_satisfaction_attrition.sum(axis=1)
    * 100
).round(2)

job_satisfaction_attrition

Attrition,No,Yes,Attrition_Rate
JobSatisfaction,,,
1,223,66,22.84
2,234,46,16.43
3,369,73,16.52
4,407,52,11.33


In [74]:
job_satisfaction_attrition = pd.crosstab(
    df["JobSatisfaction"],
    df["Attrition"]
)

job_satisfaction_attrition["Attrition_Rate"] = (
    job_satisfaction_attrition["Yes"]
    / job_satisfaction_attrition.sum(axis=1)
    * 100
).round(2)

job_satisfaction_attrition

Attrition,No,Yes,Attrition_Rate
JobSatisfaction,,,
1,223,66,22.84
2,234,46,16.43
3,369,73,16.52
4,407,52,11.33
